services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro # 'ro' means read-only, which is typical for source data
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /media/meitu001/Data/share
      o: bind